add_library(${PROJECT_NAME} STATIC IMPORTED)
find_library(CONSOLE_LIBRARY_PATH ${PROJECT_NAME} HINTS "${CMAKE_CURRENT_LIST_DIR}/../../")
set_target_properties(${PROJECT_NAME} PROPERTIES IMPORTED_LOCATION "${CONSOLE_LIBRARY_PATH}")